# 	OSM2KM4C
#   Copyright (C) 2017 DISIT Lab http://www.disit.org - University of Florence
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>. 

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX km4c: <http://www.disit.org/km4city/schema#>
PREFIX dct: <http://purl.org/dc/terms/>

CONSTRUCT {
  GRAPH <http://www.disit.org/km4city/resource/GrafoStradale/RT2OSM/Municipality/MS20170510> {
    ?tm owl:sameAs ?om .
    ?om owl:sameAs ?tm .
  }
}
WHERE {
  GRAPH <http://www.disit.org/km4city/resource/GrafoStradale/Grafo_stradale_Grosseto> {
    ?tm a km4c:Municipality ;
    dct:alternative ?ta.
  }
  GRAPH <urn:km4city:OSM:test:grosseto> {
    ?om a km4c:Municipality ;
    dct:alternative ?ta.
  }
}

